export enum EXISTING_SORTING_ALGO {
    SELECTION_SORT = 'Selection sort',
    BUBBLE_SORT = 'Bubble sort',
    INSERTION_SORT = 'Insertion sort'

}

export const SORTING_ALGORITHMS_ARRAY = [EXISTING_SORTING_ALGO.SELECTION_SORT,EXISTING_SORTING_ALGO.BUBBLE_SORT,EXISTING_SORTING_ALGO.INSERTION_SORT];



export const SORTING_SPEED_IN_MS = 500;

export const MIN_SORTING_STICK = 1;
export const MAX_SORTING_STICK = 100;

export const MIN_SORING_SPEED = 100;
export const MAX_SORING_SPEED = 3000;